# If this file's changed, run `docker-compose up --build` to rebuild
# your Docker images.

RUN apk add yarn --no-cache --repository http://dl-3.alpinelinux.org/alpine/v3.8/community/ --allow-untrusted